name: 'Candice&ZW'
favicon: null
layout_spectrum: 0.8501949175260961
typography_spectrum: 0.16117630619555712
title: Our Wedding Pictures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.826078710379079
  lightness: 0.5636546069290489
  saturation: 0.22874196665361524
  rhythmicContrast: 0.5175763133447617
purpose: []
