name: 'Candice&ZW'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.02993
title: Our Wedding Pictures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141325'
    - '#ddd4cf'
    - '#492f2e'
    - '#b5adaa'
    - '#8c7355'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
