name: 'Candice&ZW'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16117630619555712
title: Our Wedding Pictures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141325'
    - '#ddd4cf'
    - '#492f2e'
    - '#b5adaa'
    - '#8c7355'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
